apiVersion: apps/v1
kind: Deployment
metadata:
  name: asset-webhook
  namespace: poly-test
  labels:
    app: poly-asset
    chart: {{ template "doc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: poly-asset
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: asset-webhook
      release: {{ .Release.Name }}
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: asset-webhook
        release: {{ .Release.Name }}
    spec:
      affinity: {{ .Values.affinity | toJson }}
      containers:
        - name: producer
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 6100Mi
              cpu: 4100m
            requests:
              memory: 6000Mi
              cpu: 4000m
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5


